#!/bin/sh

# Wrapper for running make inside docker container
#
# Before running this do: sudo make -C docker
#
# If running `make upload` on a machine outside of EC2 you need to have AWS
# credentials passed into the docker. We use environment variables for that,
# there is a script in docker folder that will populate the environment
# variables from your usual aws config
#

get_env () {
    aa="AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN AWS_DEFAULT_REGION"
    ee=""
    for a in $aa; do
        e="${!a}"
        if [ ! -z "${e}" ]; then
            ee="-e $a=$e $ee"
        fi
    done
    echo "$ee"
}

eval $(python ./docker/aws_creds.py)

exec docker run $(get_env) --rm -v $(pwd):/src dea-build-deb "$@"
