FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install -y \
      certbot \
      python3-certbot-dns-route53 && \
    apt-get clean && \
    echo done

VOLUME /etc/letsencrypt
ENTRYPOINT ["certbot"]
