FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
      certbot python3-certbot-dns-route53 \
      python3-pip && \
    apt-get clean

RUN pip3 install awscli

COPY "dea_devbox-*whl" /tmp/
RUN pip3 install /tmp/dea_devbox-*whl

COPY "dea-ssl.sh" /usr/local/bin/

VOLUME /etc/letsencrypt
ENTRYPOINT ["/usr/local/bin/dea-ssl.sh"]
