#!/bin/bash

# make sure pip is new
pip3 install --no-cache pip --upgrade
hash -r
pip3 install --no-cache wheel setuptools
pip3 install --no-cache --upgrade dateutils

# dea-devbox tools
pip3 install --no-cache /usr/share/dea/wheels/*.whl

# used by scripts
pip3 install --no-cache jinja2-cli

# jupyter hub via pip
hash node >/dev/null 2>&1 || ln -sf /usr/bin/nodejs /usr/local/bin/node
npm install -g configurable-http-proxy
npm cache clean --force
install -D -d -m 755 /var/lib/jupyterhub/
pip3 install --no-cache \
     tornado==5.1.1 \
     jupyterhub==0.9.4 \
     oauthenticator==0.8.1 \
     jupyterlab \
     jupyterlab-git \
     dockerspawner

pip3 install --no-cache notebook

ln -sf /usr/share/dea/dea-install-datacube.sh /usr/local/bin/dea-install-datacube

echo "Enabling DEA init service"
systemctl enable dea-init.service dea-early-init.service
